# If you have OpenSSL installed, we recommend updating
# the following line to use "https"
source 'http://rubygems.org'

gem "middleman", "~>3.1.1"
gem "middleman-livereload", "~> 3.1.0"
gem "middleman-deploy", "~> 0.0.11"
gem "redcarpet" # markdown
gem "slim", "~> 1.3.6"

# Cross-templating language block fix for Ruby 1.8
platforms :mri_18 do
  gem "ruby18_source_location"
end

